import {
  FaPython,
  FaChartBar,
  FaPalette,
  FaShieldAlt,
  FaJava,
  FaCode,
} from "react-icons/fa";

export const certifications = [
  {
    id: 1,
    title: "Python Programming with Red Hat",
    issuer: "Red Hat",
    year: "2026",
    category: "Python & Automation",
    credentialId: "RH-AD141-2026",
    icon: FaPython,
    color: "from-red-500/20 to-orange-500/20",
    badgeColor: "bg-red-500/10 text-red-400 border-red-400/30",
    description:
      "Completed Red Hat's Python Programming (AD141 - RHA) enterprise training covering Python programming fundamentals, system automation, scripting, Linux environment utilities, and algorithmic problem-solving.",
    skills: [
      "Python 3",
      "Red Hat AD141",
      "Automation Scripting",
      "Data Structures",
      "Linux Utilities",
      "Problem Solving",
    ],
    highlights: [
      "Enterprise Python Architecture",
      "Automation & Scripting Workflows",
      "Red Hat Academy Standards",
    ],
    verifyUrl: "https://www.redhat.com",
  },
  {
    id: 2,
    title: "Python Programming",
    issuer: "Skill India Digital Hub & Microsoft",
    year: "2026",
    category: "Python & Automation",
    credentialId: "SIDH-MS-PY-2026",
    icon: FaPython,
    color: "from-blue-500/20 to-cyan-500/20",
    badgeColor: "bg-cyan-500/10 text-cyan-400 border-cyan-400/30",
    description:
      "Completed an intensive 40-hour Python Programming course covering core Python concepts, programming logic, modular functions, advanced data structures, OOP principles, and real-world software applications.",
    skills: [
      "Python Fundamentals",
      "OOP Concepts",
      "Modular Architecture",
      "File I/O",
      "Logic Building",
      "Microsoft Learning Track",
    ],
    highlights: [
      "40-Hour Intensive Training",
      "National Digital Skill Standard",
      "Microsoft Verified Content",
    ],
    verifyUrl: "https://www.skillindiadigital.gov.in",
  },
  {
    id: 3,
    title: "Introduction to Data Science",
    issuer: "IBM • Coursera",
    year: "2025",
    category: "Data Science & AI",
    credentialId: "IBM-DS-COURSERA-2025",
    icon: FaChartBar,
    color: "from-purple-500/20 to-indigo-500/20",
    badgeColor: "bg-purple-500/10 text-purple-400 border-purple-400/30",
    description:
      "Mastered Data Science fundamentals including Jupyter Notebook workflows, relational SQL querying, Data Science methodologies, data analysis pipelines, and analytical problem-solving.",
    skills: [
      "Data Science Methodology",
      "SQL & Relational DBs",
      "Jupyter Notebooks",
      "Data Analysis",
      "Python for Data",
      "Statistical Thinking",
    ],
    highlights: [
      "IBM Professional Foundation",
      "SQL Data Extraction & Analytics",
      "Methodology & Lifecycle Analysis",
    ],
    verifyUrl: "https://www.coursera.org",
  },
  {
    id: 4,
    title: "UI / UX Design Specialization",
    issuer: "California Institute of the Arts • Coursera",
    year: "2025",
    category: "UI / UX Design",
    credentialId: "CALARTS-UIUX-2025",
    icon: FaPalette,
    color: "from-pink-500/20 to-rose-500/20",
    badgeColor: "bg-pink-500/10 text-pink-400 border-pink-400/30",
    description:
      "Completed comprehensive UI/UX Design specialization covering interactive wireframing, high-fidelity prototyping, user research, visual design hierarchy, design systems, and user-centered design principles.",
    skills: [
      "Figma & Wireframing",
      "User Research & Personas",
      "Visual Hierarchy",
      "High-Fidelity Prototyping",
      "Design Systems",
      "Usability Testing",
    ],
    highlights: [
      "CalArts Design Specialization",
      "End-to-End Product Design Case Studies",
      "Design System Implementation",
    ],
    verifyUrl: "https://www.coursera.org",
  },
  {
    id: 5,
    title: "Web Technologies & Security",
    issuer: "Coursera",
    year: "2025",
    category: "Web & Security",
    credentialId: "COURSERA-WEBSEC-2025",
    icon: FaShieldAlt,
    color: "from-emerald-500/20 to-teal-500/20",
    badgeColor: "bg-emerald-500/10 text-emerald-400 border-emerald-400/30",
    description:
      "Learned modern web technologies, Vue.js reactive paradigms, software security practices, data security, authorization principles, and secure web application development against vulnerabilities.",
    skills: [
      "Web Application Security",
      "Authentication & JWT",
      "Vue.js Reactive Basics",
      "Secure Coding Practices",
      "RESTful API Security",
      "XSS & CSRF Prevention",
    ],
    highlights: [
      "Web Security Best Practices",
      "Modern Frontend Frameworks",
      "OWASP Security Awareness",
    ],
    verifyUrl: "https://www.coursera.org",
  },
  {
    id: 6,
    title: "Java Programming Certification",
    issuer: "Certification Course",
    year: "2024",
    category: "Core Programming",
    credentialId: "JAVA-CORE-2024",
    icon: FaJava,
    color: "from-amber-500/20 to-yellow-500/20",
    badgeColor: "bg-amber-500/10 text-amber-400 border-amber-400/30",
    description:
      "Covered Object-Oriented Programming (OOP), Java Collections Framework, Exception Handling, JDBC database connectivity, Multithreading, and Core Java application architecture.",
    skills: [
      "Java (OOP)",
      "Java Collections Framework",
      "JDBC & Database Integration",
      "Multithreading & Concurrency",
      "Exception Handling",
      "Memory Management",
    ],
    highlights: [
      "Robust Object-Oriented Architecture",
      "Multi-threaded Programming",
      "Relational Database Connectivity (JDBC)",
    ],
    verifyUrl: null,
  },
  {
    id: 7,
    title: "C Programming Certification",
    issuer: "Certification Course",
    year: "2023",
    category: "Core Programming",
    credentialId: "C-PROG-2023",
    icon: FaCode,
    color: "from-sky-500/20 to-blue-500/20",
    badgeColor: "bg-sky-500/10 text-sky-400 border-sky-400/30",
    description:
      "Learned fundamental C programming including pointer arithmetic, dynamic memory allocation, custom data structures, file I/O operations, algorithmic logic, and performance-critical systems programming.",
    skills: [
      "C Language",
      "Pointers & Memory Management",
      "Dynamic Allocation (malloc/free)",
      "Data Structures",
      "File Handling",
      "Algorithmic Logic",
    ],
    highlights: [
      "Low-Level System Concepts",
      "Memory Optimization & Pointers",
      "Foundation of Computer Science",
    ],
    verifyUrl: null,
  },
];
